site_name: DTU - Process Science Lab
site_url: https://sma4pm.github.io

nav:
  - Home: index.md
  - Members: members.md
  - Events: events.md
  - Publications: publications.md
  - Teaching: teaching.md

theme:
  name: material
  palette:
    primary: custom
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.footer
  icon:
    logo: material/home

extra_css:
  - stylesheets/extra.css

plugins:
  - include-markdown
  - markdown-exec

markdown_extensions:
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
